import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';
import { theme } from '../components/responsive';

import Header from '../components/Header'
import { ThemeProvider } from '@mui/material';
import Main from '../components/Main';

export default function Home() {
  return (
    <ThemeProvider theme={theme}>
      <div className={styles.container}>
        <Head>
          <title>Dynamox</title>
          <meta
            name="description" 
            content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      
        <Header />

        <Main />

        <footer className={styles.footer}>
        </footer>
      </div>
    </ThemeProvider>
  )
}
