import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';
import { theme } from '../components/responsive';

import Header from '../components/Header'
import { ThemeProvider } from '@mui/material';
import Main from '../components/Main';
import Sensores from '../components/Sensores';
import Footer from '../components/Footer';

export default function Home() {
  return (
    <ThemeProvider theme={theme}>
      <div className={styles.container}>
        <Head>
          <title>Dynamox</title>
          <meta
            name="description"
            content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          {/* Raleway Font */}
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
          <link href="https://fonts.googleapis.com/css2?family=Raleway&display=swap" rel="stylesheet" />
        </Head>

        <Header />
        <Main />
        <Sensores />
        <Footer />

        <footer className={styles.footer}>
        </footer>
      </div>
    </ThemeProvider>
  )
}
