

import Image from 'next/image'
import Head from 'next/head'
import Header from './Header'
import Footer from './Footer'
import styles from '../styles/Layout.module.scss'

export default function Layout({ children }) {
    return (
      <div>
        <Head>
          <meta name="description" content="Generated by create next app" />
          
        </Head>

        <Header />



        <Footer />
        
      </div>
    )
  }