import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';
import { theme } from '../components/responsive';

import Header from '../components/Header'
import { ThemeProvider } from '@mui/material';

export default function Home() {
  return (
    <ThemeProvider theme={theme}>
      <div className={styles.container}>
        <Head>
          <title>Dynamox</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      
        <Header />
        <main className={styles.main}>
          <h1>hello world</h1>
      
        </main>
        <footer className={styles.footer}>
        </footer>
      </div>
    </ThemeProvider>
  )
}
